version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: desafios_mysql
    restart: always
    tty: true
    volumes:
      - ./_mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=db_desafios
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafios-network
    ports:
      - "3306:3306"
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  desafios-network:
    driver: bridge