version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./_mysql:/var/lib/mysql/
      - ./scripts:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=db_desafios
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafios-network
    ports:
      - "3306:3306"

networks:
  desafios-network:
    driver: bridge