version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./db/_mysql:/var/lib/mysql/
      - ./db/scripts:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=db_desafios
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafios
    ports:
      - "3306:3306"

  app:
    image: ghcr.io/guisegers/fullcycle-desafio:docker-node
    build:
      context: ./app
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 50s docker-entrypoint.sh
    command: npm run start
    container_name: node
    tty: true
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - desafios
    ports: 
      - "3000:3000"
    depends_on:
      - mysql
  
  nginx:
    image: ghcr.io/guisegers/fullcycle-desafio:docker-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    tty: true
    volumes:
      - ./nginx/html:/www/data/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - desafios

networks:
  desafios:
    driver: bridge